[tool.poetry]
name = "my-ai-pa"
version = "0.1.0"
description = "My (our) personal asistant"
authors = ["Wei Hung <wayne930242@gmail.com>"]
license = "MIT"
packages = [{include = "langchain"}]

[tool.poetry.dependencies]
python = "^3.11"
openai = "^0.27.4"
python-dotenv = "^1.0.0"
loguru = "^0.7.0"
langchain = "^0.0.161"
pydantic = "^1.10.7"
fastapi = "^0.95.1"
uvicorn = "^0.22.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
